// Only the 10 products shown in Beverage Category Page HTML.html
const beverages = [
  {
    name: 'Coca-Cola',
    brand: 'Coca-Cola',
    category: 'Beverages',
    quantity: '750 ml',
    price: 65,
    originalPrice: 72,
    discount: 10,
    image: '/images/grocery_category_images/Coca-Cola.jpeg',
    description: 'Classic cola with a crisp, refreshing sparkle that pairs perfectly with meals and casual moments.',
    stock: 84,
    rating: 4.8,
    reviews: 315
  },
  {
    name: 'Thums Up',
    brand: 'Thums Up',
    category: 'Beverages',
    quantity: '750 ml',
    price: 66,
    originalPrice: 74,
    discount: 11,
    image: '/images/grocery_category_images/Thums up.jpeg',
    description: 'Bold, energising cola taste with a strong fizz and unmistakable Indian classic flavour.',
    stock: 64,
    rating: 4.6,
    reviews: 230
  },
  {
    name: 'Sprite',
    brand: 'Sprite',
    category: 'Beverages',
    quantity: '750 ml',
    price: 63,
    originalPrice: 72,
    discount: 12,
    image: '/images/grocery_category_images/Sprite.jpeg',
    description: 'Crisp lemon-lime refreshment with a sparkling bite for a cool and uplifting sip.',
    stock: 66,
    rating: 4.7,
    reviews: 248
  },
  {
    name: 'Fanta Orange',
    brand: 'Fanta',
    category: 'Beverages',
    quantity: '750 ml',
    price: 63,
    originalPrice: 72,
    discount: 12,
    image: '/images/grocery_category_images/Fanta Orange.jpeg',
    description: 'Sweet orange fizz with bright citrus flavour and a fun, refreshing finish.',
    stock: 58,
    rating: 4.5,
    reviews: 202
  },
  {
    name: 'Maaza Mango Drink',
    brand: 'Maaza',
    category: 'Beverages',
    quantity: '1.2 L',
    price: 78,
    originalPrice: 87,
    discount: 10,
    image: '/images/grocery_category_images/Mazza Mango Drink.jpeg',
    description: 'Rich, juicy mango drink with a smooth tropical taste and a satisfying fruit burst.',
    stock: 63,
    rating: 4.7,
    reviews: 238
  },
  {
    name: 'Real Mixed Fruit Juice',
    brand: 'Real',
    category: 'Beverages',
    quantity: '1 L',
    price: 98,
    originalPrice: 106,
    discount: 8,
    image: '/images/grocery_category_images/Real Mixed Fruit Juice.jpeg',
    description: 'A blend of juicy fruit flavours crafted for a refreshing, naturally fruity taste.',
    stock: 61,
    rating: 4.7,
    reviews: 219
  },
  {
    name: 'Tata Tea',
    brand: 'Tata Tea',
    category: 'Beverages',
    quantity: '500 g',
    price: 135,
    originalPrice: 148,
    discount: 9,
    image: '/images/grocery_category_images/Tata Tea.jpeg',
    description: 'Premium tea leaves with a rich aroma and smooth taste for a comforting cup every day.',
    stock: 68,
    rating: 4.8,
    reviews: 310
  },
  {
    name: 'Nescafé Classic Coffee',
    brand: 'Nescafé',
    category: 'Beverages',
    quantity: '100 g',
    price: 430,
    originalPrice: 485,
    discount: 12,
    image: '/images/grocery_category_images/Neacafe` Classic Coffee.jpeg',
    description: 'Classic instant coffee with a rich aroma and strong flavour for your daily cup.',
    stock: 34,
    rating: 4.9,
    reviews: 420
  },
  {
    name: 'Bournvita',
    brand: 'Cadbury Bournvita',
    category: 'Beverages',
    quantity: '500 g',
    price: 200,
    originalPrice: 220,
    discount: 10,
    image: '/images/grocery_category_images/Bournvita.jpeg',
    description: 'Chocolate malt health drink with a rich flavour and comforting everyday nutrition.',
    stock: 55,
    rating: 4.8,
    reviews: 341
  },
  {
    name: 'Tang Orange Drink',
    brand: 'Tang',
    category: 'Beverages',
    quantity: '500 g',
    price: 90,
    originalPrice: 98,
    discount: 8,
    image: '/images/grocery_category_images/Tang Orange Drink.jpeg',
    description: 'Bright orange flavour drink mix perfect for refreshing homemade beverages anytime.',
    stock: 62,
    rating: 4.5,
    reviews: 184
  }
];

module.exports = beverages;
